config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, :skip => [:registrations] 
    as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  # website pages
  get '/about', to: 'website#about', as: 'about'
  get '/art', to: 'art#index'
  get '/under_development', to: 'website#under_development'

  # contact
  post '/contact', to: 'contact_requests#create', as: 'contact_request'

  # projects
  get '/projects', to: 'projects#index'
  post '/projects', to: 'projects#index'
  post '/projects/update_filters', to: 'projects#update_filters'
  post '/projects/toggle_all', to: 'projects#toggle_all'
  get '/project/:id', to: 'projects#show', as: 'project'

  post 'admin/projects/sort_priority', to: 'admin/projects#sort_priority'

  namespace :admin do
    root "projects#index"
    resources :projects
    resources :categories
  end

  root "website#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :projects

    def format_category_by_id(id)
        Category.find(id).name ||= "N/A"
    end

end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
    attr_accessor :email_validation
    validates :name, :email, :message, presence: true

    validates :email, presence: true, format: Devise.email_regexp
    
end

app/models/project.rb
class Project < ApplicationRecord
    mount_uploader :image_file, ImageUploader
    has_and_belongs_to_many :categories

    validates :order, numericality: { other_than: -1 }

    def categories
        self.category_ids
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    before_action :set_category, only: %i[ show edit update destroy]

    def index
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def create 
        @category = Category.new(category_params)

        if @category.save
            redirect_to admin_categories_path
        end
    end

    def update
        if @category.update(category_params)
            redirect_to admin_categories_path
        else
            render 'edit'
        end
    end

    def destroy
    end

    private
        def set_category
            @category = Category.find(params[:id])
        end

        def category_params
            params.require(:category).permit(:name)
        end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
    before_action :set_project, only: %i[ show edit update destroy]
    before_action :set_categories, only: %i[ new edit ]

    def index
        @projects = Project.all.order(order: :asc)
    end

    def show
    end

    def new
        @project = Project.new
    end

    def edit
    end

    def create 
        @project = Project.new(project_params)

        if @project.save
            redirect_to admin_projects_path
        end
    end

    def update
        set_order(params[:project][:order])

        if @project.update(project_params)
            redirect_to admin_projects_path
        else
            render 'edit'
        end
    end

    def destroy
        @project.destroy
        redirect_to admin_projects_path
    end


    private

        def set_order(order)
            Project.where(order: order..).each do |p|
                p.order = p.order + 1
                p.save!
            end 
        end

        def set_project
            @project = Project.find(params[:id])
        end

        def set_categories
            @categories = Category.all
        end

        def project_params
            params.require(:project).permit(:name, :order, :url, :description, :image_file, :active, :category_ids => [])
        end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout "application_admin"
	before_action :require_website_admin
	

	private

        def require_website_admin
            unless current_user
                redirect_to new_user_session_path and return
            end
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def under_development
        redirect_to under_development_path
    end
end

app/controllers/art_controller.rb
class ArtController < ApplicationController
    before_action :under_development

    def index
    end
    
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController

    def index
    end

    def create
        @contact_request = ContactRequest.new(contact_request_params)
        
        respond_to do |format|
            if @contact_request.save
                ContactMailer.contact_request(@contact_request).deliver_now unless params[:email_validation].present?
                flash[:notice] = "Thanks, I'll be in touch soon!"
                format.js { render 'contact' }
            else
                if params[:contact_request][:name].blank? || params[:contact_request][:email].blank? || params[:contact_request][:message].blank? 
                    flash[:notice] = "Please correct the errors below, all fields are required."
                else
                    flash[:notice] = "Sorry, something went wrong. Please try again later."
                end

                format.js { render 'error' }
            end
        end        
    end 
    
    private
        def contact_request_params
            params.require(:contact_request).permit(:name, :email, :message, :email_validation)
        end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index
        @categories = Category.all
        
        if params[:categories].present? && !(params[:previous_categories] == params[:categories])
            @projects = Project.where(
                            id: Project.joins(:categories).where(categories: {id: params[:categories]})
                            ).where(active: true)
        else
            @projects = Project.where(active: true)
        end

        @projects = @projects.order(order: :asc)

        respond_to do |format|
            format.html 
            format.js { render 'filter' }
        end
    end

    def show
        respond_to do |format|
            format.js { render 'show' }
        end
    end

    # AJAX Actions
    def update_filters
        @categories = Category.all
        @filters_html = render_to_string(partial: 'filters', locals: {categories: @categories, selected: params[:categories] })

        render json: { 
                       filters_partial: @filters_html
                    }
    end

    def toggle_all
        @categories = Category.all
        @filters_html = render_to_string(partial: 'toggle_all', locals: {categories: @categories })

        render json: { 
                       filters_partial: @filters_html
                    }
    end
    
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController

    def index
        @contact_request = ContactRequest.new
        
        render :layout => 'homepage'
    end

    def about
        
    end

    def under_development 
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

    def get_project_image(project)
        unless project.image_file.present?
            return asset_path "circuits-rtol.svg"
        end

        begin
            return project.image_file.url
        rescue
            return asset_path "circuits-rtol.svg"
        end
    end

end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.submit %>
<% end %>

app/views/admin/categories/_table.html.erb
<table class="custom-table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
        <tr>
            <td><%= category.try(:name) %></td>
            <td class="action-td">
                  <%= button_to admin_category_path(category), :method => :delete, class: 'btn btn-action btn-delete', data: { confirm: 'Are you sure?' } do %>
                      <i class="fas fa-trash-alt"></i>
                  <% end %>
                  <%= link_to edit_admin_category_path(category) do %>
                    <i class="fas fa-pencil"></i>
                  <% end %>
                  <%= link_to admin_category_path(category), class: 'btn btn-action btn-view'  do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
            </td>
        </tr>
    <% end %>
  </tbody>
</table>

<style>

.action-td {
    text-align: end;
}

form.button_to {
    display: inline-flex;
}

table {
    width: 100%;
}

</style>

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<div class="row">
    <div class="col-6">
    <%= render 'admin/shared/header', title: 'Categories' %>
    </div>
    <div class="col-6 text-end">
        <%= link_to new_admin_category_path, class: 'btn btn-round btn-lg btn-main' do %>Add Category<% end %>
    </div>
</div>

<%= render 'table' %>

app/views/admin/categories/new.html.erb
<%= render 'form' %>

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :image_file %>
    <%= f.file_field :image_file, value: @project.image_file ||= "", accept: 'image/x-png,image/gif,image/jpeg' %>
    <div>
    <% if @project.image_file.present? %>
        Current: <%= @project.image_file %>
    <% end %>
    </div>

    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>

    <%= f.label :categories %>
    <%= collection_select(:project, :category_ids, @categories, :id, :name, {}, { multiple: true, class: "form-control form-control-lg", id: 'tag-select' }) %>

    <%= f.label :order %>
    <%= f.number_field :order, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: '10', class: 'form-control' %>


    <%= f.label :active %>
    <%= f.check_box :active %>

    <%= f.submit %>
<% end %>

app/views/admin/projects/_table.html.erb
<table class="custom-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody id="projects-table" data-update-url="<%= admin_projects_sort_priority_path %>" >
    <% @projects.each do |project| %>
        <tr id="project-<%= project.id %>">
            <td><%= project.try(:name) %></td>
            <td><%= project.try(:order) %></td>
            <td>
                <% if project.categories.count > 0 %>
                  <% project.categories.each do |c| %>
                      <span class="me-2"><%= Category.find(c).name || "N/A" %></span>
                  <% end %>
                <% end %>
            </td>
            <td class="action-td">
                <%= button_to admin_project_path(project), :method => :delete, class: 'btn btn-action btn-delete', data: { confirm: 'Are you sure?' } do %>
                    <i class="fas fa-trash-alt"></i>
                <% end %>
                <%= link_to edit_admin_project_path(project) do %>
                  <i class="fas fa-pencil"></i>
                <% end %>
                <%= link_to admin_project_path(project), class: 'btn btn-action btn-view'  do %>
                  <i class="fas fa-eye"></i>
                <% end %>
            </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/projects/edit.html.erb
<%= render 'form' %>

app/views/admin/projects/index.html.erb
<div class="row">
    <div class="col-6">
    <%= render 'admin/shared/header', title: 'Projects' %>
    </div>
    <div class="col-6 text-end">
        <%= link_to new_admin_project_path, class: 'btn btn-round btn-lg btn-main' do %>Add Project<% end %>
    </div>
</div>

<%= render 'table' %>

app/views/admin/projects/new.html.erb
<%= render 'form' %>

app/views/admin/shared/_header.html.erb
<div class="page-header">
    <h1 class="section-title"><%= title %></h1>
</div>

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml.erb' %>">
<meta name="theme-color" content="#ffffff">

app/views/art/_under_development.html.erb
<section class="under-development">
    <%= image_tag 'circuit-board--lg.svg', class: 'bg-element w-100 h-100 object-fit-cover' %>
    <div class="row centered w-100">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="content-card">
                <h1 class="section-title">Under Development</h1>
            </div>
        </div>
        <div class="col-3">
        </div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-4 p-relative">
            <%= image_tag 'circuit-board--lg.svg', class: 'bg-element bg-green bg-inset-shadow' %>
        </div>
        <div class="col-4"></div>
    </div>
</section>


<style>

.p-relative {
    position: relative;
}

.bg-green {
    background: #287b61;
    width: 100%;
    height: 50vh;
    min-height: 500px;
    top: 5rem;
}

.centered {
  position: fixed;
  top: 50%;
  left: 50%;
  /* bring your own prefixes */
  transform: translate(-50%, -50%);
}

.content-card {
    padding: 2rem;
    z-index: 1;
    background: white;
    box-shadow: 0px 0px 90px rgba(0, 0, 0, 0.3);
}

.bg-element {
    object-fit: cover;
    position: absolute;
    z-index: -1;
}

.under-development {
    position: relative;
    background: #b8e8b32b;
    height: 100vh;
    width: 100vw;
    z-index: -2;
}

</style>

app/views/art/index.html.erb
<%= render 'under_development' %>

app/views/contact_requests/_contact.html.erb
<div class="notice <%= flash[:error].present? ? 'error' : nil %> animate-slide-down">
    <%= flash[:error].present? ? flash[:error] : flash[:notice] %>
    <button class="dismiss ms-3">&times</button>
    <div class="progress">
        <div class="bar"></div>
    </div>
</div>


<style>

.dismiss {
    opacity: 0.4;
    font-weight: 100;
    outline: none;
    background: none;
    border: none;
    color: white;
}

.dismiss:hover {
    opacity: 1;
}

.notice {
    position: fixed;
    top: 2rem;
    right: 2rem;
    //background: lightblue;
    //color: #3c4a4e;
    background: #297b62;
    color: white;
    padding: 1rem 2rem;
    border-radius: 2px;
    z-index: 999;
    transition: all 2s ease-in;
    font-size: 1.5rem;
    font-weight: 600;
    box-shadow: 0px 0px 30px rgb(0 0 0 / 20%);
}

@media (max-width: 567px) {
  .notice {
      top: 1rem;
      right: 1rem !important;
      left: 1rem !important;
  }
}

.progress {
	width: 100%;
	background-color: white;
	position: absolute;
	bottom: 5px;
	left: 0;
	right: 0;
	border-radius: 0px;
	height: 10px;
  }
  
.progress, .bar {
	height: 3px;
}

.bar {
    transition: all 5s ease-in;
	width: 1%;
    background-color: #8cd388;
    animation: fill-bar 5s ease;
    animation-fill-mode: forwards;
}

@keyframes fill-bar {
    from {
        width: 1%;
    }

    to {
        width: 100%;
    }
}


.animate-slide-up {
    animation: slide-up 1s ease !important;
    animation-fill-mode: forwards;
    opacity: 0;
}

.animate-slide-down {
	animation: slide-down 1s ease;
	animation-fill-mode: forwards;
}

@keyframes slide-down {
	from {
	  opacity: 0;
	  transform: translateY(-100px);
	}
	to {
	  opacity: 1;
	  transform: translateY(0px);
	}
}


@keyframes slide-up {
	from {
	  opacity: 1;
	  transform: translateY(0);
	}
	to {
	  opacity: 0;
	  transform: translateY(-100px);
	}
}

</style>


<style>


.dismiss {
    opacity: 0.4;
    font-weight: 100;
    outline: none;
    background: none;
    border: none;
    color: white;
}

.dismiss:hover {
    opacity: 1;
}

.notice.error {
    font-size: 1rem;
    background: #202021;
}

.notice.error .bar {
    background: #297b62;
}

.notice {
    position: fixed;
    top: 2rem;
    right: 2rem;
    background: #297b62;
    color: white;
    padding: 1rem 2rem;
    border-radius: 2px;
    z-index: 999;
    transition: all 2s ease-in;
    font-size: 1.5rem;
    font-weight: 600;
    box-shadow: 0px 0px 30px rgb(0 0 0 / 20%);
}

.progress {
	width: 100%;
	background-color: white;
	position: absolute;
	bottom: 5px;
	left: 0;
	right: 0;
	border-radius: 0px;
	height: 10px;
  }
  
.progress, .bar {
	height: 3px;
}

.bar {
    transition: all 5s ease-in;
	width: 1%;
    background-color: #8cd388;
    animation: fill-bar 5s ease;
    animation-fill-mode: forwards;
}

@keyframes fill-bar {
    from {
        width: 1%;
    }

    to {
        width: 100%;
    }
}


.animate-slide-up {
    animation: slide-up 1s ease !important;
    animation-fill-mode: forwards;
    opacity: 0;
}

.animate-slide-down {
	animation: slide-down 1s ease;
	animation-fill-mode: forwards;
}

@keyframes slide-down {
	from {
	  opacity: 0;
	  transform: translateY(-100px);
	}
	to {
	  opacity: 1;
	  transform: translateY(0px);
	}
}


@keyframes slide-up {
	from {
	  opacity: 1;
	  transform: translateY(0);
	}
	to {
	  opacity: 0;
	  transform: translateY(-100px);
	}
}


</style>

app/views/contact_requests/contact.js.erb
setTimeout(function() {
    $('button[type="submit"').html("Get in Touch");
    $('button[type="submit"').prop("disabled", false);

    $('.fill-with-message').html("<%= escape_javascript render('contact') %>");
    setTimeout(function() {
      $('.notice').addClass('animate-slide-up')
    }, 5000)
    
    $('.dismiss').on('click', function() {
        $('.notice').addClass('animate-slide-up');
    })

}, 1000);

app/views/contact_requests/error.js.erb
setTimeout(function() {
    $('button[type="submit"').html("Get in Touch");
    $('button[type="submit"').prop("disabled", false);

    $('.fill-with-message').html("<%= escape_javascript render('error') %>");
    setTimeout(function() {
        $('.notice').addClass('animate-slide-up')
    }, 5000)

    $('.dismiss').on('click', function() {
        $('.notice').addClass('animate-slide-up');
    })

    $('.form-container').html("<%= escape_javascript render('website/form') %>");
}, 1000);

app/views/layouts/admin/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light container-fluid">
  <a class="navbar-brand" href="#">
    <%= image_tag 'logo-dark.svg', style: 'width: 50px;' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
      <%= link_to admin_categories_path, class: "dropdown-item" do %>Categories<% end %>
      </li>
      <li class="nav-item dropdown">
          <%= link_to admin_projects_path, class: "dropdown-item" do %>Projects<% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Megan Nelson</title>
    <%= render 'application/favicon' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/shared/analytics' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= action_name %> <%= controller_name %>" data-turbolinks="false">
    <div class="fill-with-message"></div>
    <%= render 'layouts/shared/navigation' %>
    <div class="container-fluid px-0 overflow-hidden">
      <%= yield %>
      <%= render 'layouts/shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/shared/_navigation.html.erb
<nav id="secondary-nav" class="navbar navbar-expand-lg navbar-transparent navbar-abs pt-4">
  <div class="container px-0">
      <%= link_to root_path do %>
        <%= image_tag 'logo-dark.png', class: 'logo', width: '50px' %>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
      <div class="collapse navbar-collapse mb-2" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-lg-0">
          <li class="nav-item">
            <div class="link">
              <%= link_to about_path, class: 'nav-link active' do %>About Me<% end %>
              <span></span>
            </div>
          </li>
          <li class="nav-item">
            <div class="link">
              <%= link_to projects_path, class: 'nav-link' do %>Projects<% end %>
              <span></span>
            </div>
          </li>
          <li class="nav-item">
            <div class="link">
              <%= link_to art_path, class: 'nav-link' do %>Art<% end %>
              <span></span>
            </div>
          </li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/shared/_navigation_homepage.html.erb
<nav id="main-nav" class="navbar navbar-expand-md navbar-transparent navbar-abs">
  <div class="container-fluid px-0">
    <div class="col-12 col-md-5 padded-section p-relative">
      <%= link_to root_path do %>
        <%= image_tag 'logo-light.png', class: 'logo', width: '100px' %>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
    </div>
    <div class="col-12 col-md-7 padded-section">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <div class="link">
                  <%= link_to about_path, class: 'nav-link active' do %>About Me<% end %>
                  <span></span>
                </div>
              </li>
              <li class="nav-item">
                <div class="link">
                  <%= link_to projects_path, class: 'nav-link' do %>Projects<% end %>
                  <span></span>
                </div>
              </li>
              <li class="nav-item">
                <div class="link">
                  <%= link_to art_path, class: 'nav-link' do %>Art<% end %>
                  <span></span>
                </div>
              </li>
            </ul>
          </div>
        </div>
    </div>

</nav>

app/views/layouts/shared/_page_header.html.erb
<section class="page-header container">
    <div class="row">
        <div class="col-4">
            <%= image_tag 'circuit-board--lg.svg', class: 'object-fit-cover bg-lightgreen' %>
        </div>
        <div class="col-8">
        </div>
    </div>
</section>

app/views/projects/_filters.html.erb
<%= form_tag projects_path, :id => "filter-form", remote: true do |f| %>
    <% if params[:categories].present? %>
        <%= select_tag "previous_categories[]", options_for_select(params[:categories].compact_blank, params[:categories].compact_blank), {multiple: true, class: 'd-none'} %>
    <% end %>
    <div class="filters">
        <ul class="unstyled-list horizontal-list">
            <li>
                <%= check_box_tag "toggle_all", "all", selected.blank? ? true : false %>
                <label for="toggle_all" class='btn filter-btn'>
                    All
                </label>
            </li>
            <% @categories.all.each do |c| %>
                <li>
                    <%= check_box_tag "categories[]", c.id, params[:categories].present? && params[:categories].include?(c.id.to_s), {id: "categories_#{c.id}"} %>
                    <label for="categories_<%= c.id %>" class='btn filter-btn'>
                        <%= c.name %>
                    </label>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/projects/_projects.html.erb
<% if defined?(projects) && projects.count > 0 %>
    <div class="projects-slider">
        <% projects.each_with_index do |p, i| %>
            <div class="project-slide slide project-container">
                <div class="row">
                    <div class="col-12 col-lg-4">
                    <div class="project-name d-lg-none no-text-overflow"><%= p[:name].titleize %></div>
                        <div id="project-<%= p.id %>" class="square project-detail mb-3 pe-3">
                            <div class="project-details pt-3" style="z-index: 99;">
                                <%= link_to project_path(p), remote: true do %>
                                    <div class="project-image-container" style="z-index: 1 !important;">
                                    <div class="actions">
                                        <% if p.url.present? %>
                                            <%= link_to p.url,  target: '_blank', class: 'btn btn-md btn-shadow btn-tag btn-round' do %>
                                                <i class="fas icon fa-external-link me-3"></i>Website
                                            <% end %>
                                        <% end %>
                                    </div>
                                <% end %>
                                <img src="<%= get_project_image(p) %>" class='w-100 h-100 project-img' />
                                <%#= image_tag 'get_project_image(p)', class: 'w-100 h-100 project-img' %>
                                <span class="project-overlay"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-8">
                        <div class="project-content">
                        <div class="project-name d-none d-lg-inline-block no-text-overflow"><%= p[:name].titleize %></div>
                        <div class="description" style="z-index: 0 !important;">
                        <% if p.description.present? %>
                                <%= p.description %>
                        <% else %>
                        <%= LoremIpsum.lorem_ipsum(words: 50) %>                 
                        <% end %>
                        
                        </div>
                    </div>    
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% else %>
    <div class="card-content no-content d-flex align-items-center justify-content-center project-container">
        Nothing matches the current filter.
    </div>
<% end %>

app/views/projects/_toggle_all.html.erb
<%= form_tag projects_path, :id => "filter-form", remote: true do |f| %>
    <% if params[:categories].present? %>
        <%= select_tag "previous_categories[]", [], {multiple: true, class: 'd-none'} %>
    <% end %>
    <div class="filters">
        <ul class="unstyled-list horizontal-list">
            <li>
                <%= check_box_tag "toggle_all", "all", true %>
                <label for="toggle_all" class='btn filter-btn'>
                    All
                </label>
            </li>
            <% @categories.all.each do |c| %>
                <li>
                    <%= check_box_tag "categories[]", c.id, false, {id: "categories_#{c.id}"} %>
                    <label for="categories_<%= c.id %>" class='btn filter-btn'>
                        <%= c.name %>
                    </label>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>